### ISSUE TITLE
Hashed library builds - environment variables

### ISSUE THREAD

**Issue by frankdownunder** [SmingHub/Sming#1758]
With regard to to hashed library builds - #1724, I noticed the following sllghtly quirky thing:
cd Basic_Blink
export SMING_ARCH=Host
make
export SMING_ARCH=Esp8266
make

I would have expected the second invocation of make to use the different Arch setting.  Passing it on the command line works as expected.

**Comment by mikee47** [comment]
If you haven't found `Sming/building.md` have a read, hopefully make things clearer.

This behaviour is by design. Cached variables always take priority over the environment (including project makefile / component.mk settings and Eclipse). Some advantages:

* Switching between eclipse and CLI is simpler because they'll use the same settings, regardless of what's been set elsewhere.
* Variables are stored with each project (and build type)
* If computer is rebooted, crashes, etc. you can get straight back to where you were without having to run a load of `exports`.

To get your example to work, do this:

```
cd Basic_Blink
export SMING_ARCH=Host
make
export SMING_ARCH=Esp8266
make config-clean
make
```
