### ISSUE TITLE
How to use std::exception?

### ISSUE THREAD

**Issue by m3x1m0m** [SmingHub/Sming#1973]
Somewhere in **$SMING_HOME/Arch/Esp8266/build.mk** the flag **-fno-exceptions** is added. When changing it to **-fexceptions** and recompiling Sming the linker has undefined references to e.g.  **`_Unwind_Resume'**.

Has anybody ever tried to work with std::exception in Sming? Programming with exceptions is rather convenient compared to returning error codes or similar.

**Comment by mikee47** [comment]
IMHO exception handling is more useful in threaded environments because the constructor/destructor code is often all in the same place. It's a good way to handle complexity in some situations. But not all. It can be costly in terms of RAM and performance because of the hidden setup/teardown code.

One situation where exception handling can be useful is in support of third-party libraries which expect it, though you can sometimes fake it using `setjmp` and `longjmp`.

Exceptions are supported as a build option for [ESP8266 Arduino](https://github.com/esp8266/arduino) and Sming is migrating to their toolchain (see #1825) which should allow us to do the same for those who wish to try it.
