### ISSUE TITLE
Documentation should recommend git clone --recursive so libraries are downloaded

### ISSUE THREAD

**Issue by hugows** [SmingHub/Sming#850]
In this page https://github.com/SmingHub/Sming/wiki/Linux-Quickstart:

it seems it would be better to list:

git clone --recursive https://github.com/SmingHub/Sming.git

Everything compiles now...
Cheers, just trying this cool project!

**Comment by slaff** [comment]
@hugows Actually that is wrong. The 'makefile' mechanism takes care to fetch on demand the needed submodules and patch them.  If you pre-pull them using `--recursive` the source code will not be patched and most probably will work only with esp-open-sdk.

**Comment by juppin** [comment]
I have this idea today too, because if i cd to Sming/Sming after cloning the repo without --recursive make shows an error that path isn´t correct.

`user@ubuntu:/opt/Sming/Sming$ make
Fetching third-party/rboot/ ...
Submodul 'Sming/rboot' (https://github.com/raburton/rboot.git) für Pfad 'third-party/rboot' in die Konfiguration eingetragen.
Klone nach 'Sming/third-party/rboot' ...
remote: Counting objects: 345, done.
remote: Total 345 (delta 0), reused 0 (delta 0), pack-reused 345
Empfange Objekte: 100% (345/345), 98.74 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (223/223), Fertig.
Prüfe Konnektivität ... Fertig.
Submodul-Pfad: 'third-party/rboot': '81caa867dbfbb2447b0af66c8110bb8641d8c29d' ausgecheckt
fatal: kann Patch '/opt/sming/Sming/third-party/.patches/rboot.patch' nicht öffnen: Datei oder Verzeichnis nicht gefunden
Makefile:366: die Regel für Ziel „third-party/rboot/Makefile“ scheiterte
make: [third-party/rboot/Makefile] Fehler 128 (ignoriert)
make[1]: *** /opt/sming/Sming: Datei oder Verzeichnis nicht gefunden.  Schluss.
Makefile:366: die Regel für Ziel „third-party/rboot/Makefile“ scheiterte
make: *** [third-party/rboot/Makefile] Fehler 2`

But now i see only the path isn´t correct. The folder in path is named "Sming" and not "sming" after clone of repo.
That should only be changed in the Makefile(s).

I have edited the Makefile in Sming/Sming to the correct path and now it works to make without "--recursive" cloning.
In Makefile-rboot.mk there is also the path with "sming" instead of "Sming". Other files i dont have checked.

**Comment by hugows** [comment]
Ok then I must have skipped something else in the tutorial. Will try again.. thanks.

**Comment by slaff** [comment]
> Ok then I must have skipped something else in the tutorial. Will try again.. thanks.

@hugows Anyway we should update the docs and add this information there. Thanks for pointing this out.

**Comment by slaff** [comment]
Updated the Wiki to reflect this.
